name: Build Images

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build 'urban-heat-service'
        uses: docker/build-push-action@v6
        with:
          push: true
          target: service
          tags: ghcr.io/damienallen/urban-heat-service:latest
          cache-from: type=gha
          cache-to: type=gha

      - name: Build 'urban-heat-static'
        uses: docker/build-push-action@v6
        with:
          push: true
          target: static
          tags: ghcr.io/damienallen/urban-heat-static:latest
          cache-from: type=gha
          cache-to: type=gha

  push-tag:
    name: Push Tag
    runs-on: ubuntu-24.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-tag and push 'urban-heat-service' with tag
        uses: docker/build-push-action@v6
        with:
          push: true
          target: service
          tags: ghcr.io/damienallen/urban-heat-service:${{ github.ref_name }}
          cache-from: type=gha

      - name: Re-tag and push 'urban-heat-static' with tag
        uses: docker/build-push-action@v6
        with:
          push: true
          target: static
          tags: ghcr.io/damienallen/urban-heat-static:${{ github.ref_name }}
          cache-from: type=gha
